Dodanie Entrusta
akai-org/trios pull request #29
Opened 2016-12-30 14:12 UTC by knopers666

Signed-off-by: knopers666 <knopers.priv@gmail.com>

2017-01-05 12:52 UTC, marcinlawnik requested changes

2017-01-05 12:52 UTC, marcinlawnik commented on config/cache.php
> +    'default' => env('CACHE_DRIVER', 'array'),
Dlaczego? Tzn. Jak chcesz zmienić driver na inny to robisz to w pliku `.env`.
I wydajnościowo wydaje mi się że trzymanie tego w pamięci nie ma sensu. Pliki jednak się lepiej nadają (a serwer i tak mamy z SSD)

2017-01-05 12:52 UTC, marcinlawnik commented on database/seeds/DatabaseSeeder.php
> +        //$this->call(EntrustSeeder::class);
Teraz do każdej komendy z migrate i seed trzebaby podać nazwę klasy z seederem. Seedery zostawiamy na developent tylko, chyba że ten entrust seeder coś ważnego robi?

2017-01-05 12:52 UTC, marcinlawnik commented on database/seeds/DatabaseSeeder.php
> +        //$this->call(EntrustSeeder::class);
Więc ja bym je odkomentował ;) Bo teraz widzę `EntrustSeeder` do developmentu też jest

2017-01-06 22:36 UTC, knopers666 commented on config/cache.php
> +    'default' => env('CACHE_DRIVER', 'array'),
Wywala błąd pisali na githubie, żeby zmienić i faktycznie pomogło

2017-01-06 22:37 UTC, merged